### ISSUE TITLE
configurable database

### ISSUE THREAD

**Issue by tanner0101** [vapor/redis-provider#15]
add a configurable database property on redis cache that sets each new client connection to the db

**Comment by vzsg** [comment]
It seems some of this got into the master branch, unfortunately in a broken state.

There's no `DATABASE` command in Redis, so setting the `redis.database` config key to a valid integer explodes during provider registration. Replacing the command with the correct `SELECT` is not enough either, as this has to be called per-client instead once for an otherwise quickly deallocated client.

The whole Database ordeal should be moved to the RedisCache class and added to the client factory closure.
